### ISSUE TITLE
rmvpe.pt is missing, not in model download script

### ISSUE THREAD

**Issue by RinLovesYou** [Mangio621/Mangio-RVC-Fork#88]
try running inference with it, and get a `FileNotFoundError: [Errno 2] No such file or directory: 'rmvpe.pt'` 
Could not find it in install scripts, so no idea where to get it or where to place it.

**Comment by forest-cat** [comment]
You have to download the 7zip file from their [huggingface repo](https://huggingface.co/MangioRVC/Mangio-RVC-Huggingface/tree/main). After unzipping the file using 7zip you should find the file in the root directory of the repository, copy it into the root directory of the repo youre currently working with and it should work all fine

**Comment by RinLovesYou** [comment]
You do not have to get the zip. Latest commit adds it do the make file, like every other model.

**Comment by Eipckz** [comment]
If you ever get this issue, the way I was able to fix this was by simply renaming the Host Folder my Mangio thing was in from being originally in RVC V2 to simply RVC.

So now my folder path looks like C:\Users\XXXXXX\Desktop\RVC\Mangio-RVC-v23.7.0
Rather than before it was C:\Users\XXXXXXX\Desktop\RVC V2\Mangio-RVC-v23.7.0

For some reason, it hated the whole, " V2" thing, so just rename that. Mainly adding this so that anyone else who has this issue can quickly rectify it if encountered.
